#This script takes the two bipartite networks and outputs "Table1: Summary statistics for the bipartite networks of Denmark and Italy" in Latex format.
import pandas as pd
df = pd.read_csv("danish_network/danish_bipartite.tsv", sep = "\t", dtype = {"band": str})
df2 = pd.read_csv("italian_network/italian_bipartite.tsv", sep = "\t", dtype = {"band": str})


df["artist"] = df["artist"].str.strip()
df["artist"] = df["artist"].str.replace("’", "'")
df["band"] = df["band"].str.strip()
df["band"] = df["band"].str.replace("’", "'")
df = df[["artist", "band", "year"]].drop_duplicates()

df2["artist"] = df2["artist"].str.strip()
df2["artist"] = df2["artist"].str.replace("’", "'")
df2["band"] = df2["band"].str.strip()
df2["band"] = df2["band"].str.replace("’", "'")
df2 = df2[["artist", "band", "year"]].drop_duplicates()

print("\\begin{table}")
print("\\centering")
print("\\caption{Summary statistics for the bipartite networks of Denmark and Italy.}")
print("\\begin{tabular}{c c}")
print("\\begin{tabular}{l|r}")
print("\\multicolumn{2}{c}{\\textbf{Denmark}} \\\\")
print("\\hline")
print("Variable & Value\\\\")
print("\\hline")
print(f"\\# Bands & {df['band'].drop_duplicates().shape[0]:,}\\\\")
print(f"\\# Artists & {df['artist'].drop_duplicates().shape[0]:,}\\\\")
print(f"\\# Edges & {df.shape[0]:,}\\\\")
print(f"\\# Years & {df['year'].drop_duplicates().shape[0]:,}\\\\")
print(f"\\# Band AVG Year & {df[['band', 'year']].drop_duplicates().shape[0] / df['band'].drop_duplicates().shape[0]:.1f}\\\\")
print("\\end{tabular}")
print("&")
print("\\begin{tabular}{l|r}")
print("\\multicolumn{2}{c}{\\textbf{Italy}} \\\\")
print("\\hline")
print("Variable & Value\\\\")
print("\\hline")
print(f"\\# Bands & {df2['band'].drop_duplicates().shape[0]:,}\\\\")
print(f"\\# Artists & {df2['artist'].drop_duplicates().shape[0]:,}\\\\")
print(f"\\# Edges & {df2.shape[0]:,}\\\\")
print(f"\\# Years & {df2['year'].drop_duplicates().shape[0]:,}\\\\")
print(f"\\# Band AVG Year & {df2[['band', 'year']].drop_duplicates().shape[0] / df2['band'].drop_duplicates().shape[0]:.1f}\\\\")
print("\\end{tabular}")
print("\\end{tabular}")
print("\\label{tab:summary-bipartite}")
print("\\end{table}")